### ISSUE TITLE
Using the model without ReusableEmbedding and TiedOutputEmbedding

### ISSUE THREAD

**Issue by gregory112** [kpot/keras-transformer#19]
Hi, I just want to ask how to use the model without using these embedding layers. I tried to write it like this and got an exception.

```python
x = np.array([[1, 1, 1]] * 1000)
y = np.array([[1]] * 1000)

input_layer = Input(shape=x.shape[1:], dtype='int32', name="input_layer")

transformer_layer = TransformerBlock(name="transformer", num_heads=2, use_masking=True, vanilla_wiring=False,
                                     residual_dropout=0.1, attention_dropout=0.1)

coordinate_embedding_layer = TransformerCoordinateEmbedding(1, name='coordinate_embedding')

transformer_act_layer = TransformerACT(name='adaptive_computation_time')

output_avg = Lambda(lambda in_x: K.mean(in_x, axis=1), name='avg_layer')
output_softmax_layer = Softmax(name='output_softmax')

next_step_input = input_layer
next_step_input = coordinate_embedding_layer(next_step_input, step=0)
next_step_input = transformer_layer(next_step_input)
next_step_input, act_output = transformer_act_layer(next_step_input)

transformer_act_layer.finalize()

final_output = output_softmax_layer(inputs=output_avg(act_output))

model = Model(inputs=[input_layer], outputs=[final_output])

optimizer = Adam(
    lr=0.1, beta_1=0.6, beta_2=0.999)

model.compile(
    optimizer,
    loss=sparse_categorical_crossentropy,
    metrics=["accuracy"])
```

I got exception like this

```Traceback (most recent call last):
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try.py", line 64, in <module>
    main()
  File "try.py", line 35, in main
    next_step_input = coordinate_embedding_layer(next_step_input, step=0)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/gregory112/go/src/keras-transformer/keras_transformer/position.py", line 113, in build
    trainable=True)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/keras/initializers.py", line 112, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 4139, in random_uniform
    dtype=dtype, seed=seed)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py", line 239, in random_uniform
    shape = _ShapeTensor(shape)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py", line 44, in _ShapeTensor
    return ops.convert_to_tensor(shape, dtype=dtype, name="shape")
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/gregory112/go/src/keras-transformer/venv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, 3). Consider casting elements to a supported type.
```

In my case, those ones in the x (the input dataset) will all be one-hot encoded so I think I can skip the ReusableEmbedding layer part. How can I do this?

**Comment by gregory112** [comment]
I changed the dtype of input to float32 and reshaped the input data and now it's working.
